/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms.view;

import hms.controller.EmergencyContactController;
import hms.controller.PatientContactController;
import hms.controller.PatientController;
import hms.model.EmergencyContact;
import hms.model.Patient;
import hms.model.PatientContact;
import hms.other.IDGenerator;
import static hms.view.Home.homePanel;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Manasha
 */
public class PatientDetails extends javax.swing.JPanel {

    /**
     * Creates new form PatientDetails
     */
    public PatientDetails() {
        initComponents();
        try {
            fillPatientIdText();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(PatientDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dateComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nicText = new javax.swing.JTextField();
        monthComboBox = new javax.swing.JComboBox<>();
        patientIdText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alergyDetailsText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lastNameText = new javax.swing.JTextField();
        bloodGroupTest = new javax.swing.JTextField();
        yearComboBox = new javax.swing.JComboBox<>();
        firstNameText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        specialNotesText = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        mobileTest = new javax.swing.JTextField();
        residenceTest = new javax.swing.JTextField();
        cityText = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        codeText = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        streetText = new javax.swing.JTextField();
        districtText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        relationshipText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        eMobileText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        eResidenceText = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cuprum", 1, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 208, 124));
        jLabel1.setText("Patient Details");

        updateButton.setBackground(new java.awt.Color(36, 208, 124));
        updateButton.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.setBorder(null);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cuprum", 1, 18), new java.awt.Color(57, 67, 92))); // NOI18N

        dateComboBox.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        dateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dateComboBox.setBorder(null);
        dateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(57, 67, 92));
        jLabel3.setText("Birth date: ");

        jLabel13.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(57, 67, 92));
        jLabel13.setText("Date: ");

        jLabel20.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(57, 67, 92));
        jLabel20.setText("Gender: ");

        nicText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N

        monthComboBox.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        monthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        monthComboBox.setBorder(null);
        monthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthComboBoxActionPerformed(evt);
            }
        });

        patientIdText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        patientIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIdTextActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(57, 67, 92));
        jLabel12.setText("Alergy Details: ");

        jLabel4.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(57, 67, 92));
        jLabel4.setText("First name: ");

        jLabel14.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(57, 67, 92));
        jLabel14.setText("Year: ");

        alergyDetailsText.setColumns(20);
        alergyDetailsText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        alergyDetailsText.setRows(5);
        jScrollPane2.setViewportView(alergyDetailsText);

        jLabel2.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 67, 92));
        jLabel2.setText("Patient ID: ");

        jLabel18.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(57, 67, 92));
        jLabel18.setText("Blood group: ");

        lastNameText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        lastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextActionPerformed(evt);
            }
        });

        bloodGroupTest.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        bloodGroupTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupTestActionPerformed(evt);
            }
        });

        yearComboBox.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        yearComboBox.setBorder(null);

        firstNameText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(57, 67, 92));
        jLabel9.setText("Month: ");

        jLabel7.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(57, 67, 92));
        jLabel7.setText("Special Notes: ");

        specialNotesText.setColumns(20);
        specialNotesText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        specialNotesText.setRows(5);
        jScrollPane1.setViewportView(specialNotesText);

        jLabel5.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(57, 67, 92));
        jLabel5.setText("Last name:");

        genderComboBox.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel19.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(57, 67, 92));
        jLabel19.setText("NIC: ");

        searchButton.setBackground(new java.awt.Color(36, 208, 124));
        searchButton.setFont(new java.awt.Font("Cuprum", 0, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(1, 1, 1)
                        .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(firstNameText, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patientIdText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bloodGroupTest, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(bloodGroupTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(91, 91, 91))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(72, 72, 72)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(38, 38, 38))
                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel12)
                            .addGap(33, 33, 33))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(jLabel18))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(patientIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(searchButton))
                                        .addGap(18, 18, 18)
                                        .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel14)
                                                .addComponent(monthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel13)
                                                .addComponent(dateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9)))
                                        .addGap(18, 18, 18)
                                        .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cuprum", 1, 18), new java.awt.Color(57, 67, 92))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(57, 67, 92));

        jLabel8.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(57, 67, 92));
        jLabel8.setText("Residence: ");

        jLabel11.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(57, 67, 92));
        jLabel11.setText("Address:");

        jLabel15.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(57, 67, 92));
        jLabel15.setText("Mobile: ");

        mobileTest.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        mobileTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileTestActionPerformed(evt);
            }
        });

        residenceTest.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        residenceTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residenceTestActionPerformed(evt);
            }
        });

        cityText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        cityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(57, 67, 92));
        jLabel21.setText("City:");

        jLabel24.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(57, 67, 92));
        jLabel24.setText("Postal Code:");

        codeText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        codeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeTextActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(57, 67, 92));
        jLabel22.setText("Street:");

        streetText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        streetText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetTextActionPerformed(evt);
            }
        });

        districtText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        districtText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtTextActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(57, 67, 92));
        jLabel10.setText("Discrict:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mobileTest, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(50, 50, 50)
                        .addComponent(cityText))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codeText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel22)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(districtText)
                    .addComponent(streetText)
                    .addComponent(residenceTest, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(residenceTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mobileTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(streetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(districtText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(codeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "In Case of Emergency", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cuprum", 1, 18), new java.awt.Color(57, 67, 92))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(57, 67, 92));

        jLabel23.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(57, 67, 92));
        jLabel23.setText("Name: ");

        jLabel26.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(57, 67, 92));
        jLabel26.setText("Next if kin: ");

        relationshipText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        relationshipText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationshipTextActionPerformed(evt);
            }
        });

        nameText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        eMobileText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        eMobileText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMobileTextActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(57, 67, 92));
        jLabel16.setText("Mobile: ");

        jLabel17.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(57, 67, 92));
        jLabel17.setText("Residence: ");

        eResidenceText.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        eResidenceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eResidenceTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel23))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameText, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(relationshipText))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(eMobileText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eResidenceText, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(relationshipText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(eResidenceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eMobileText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        nextButton.setBackground(new java.awt.Color(36, 208, 124));
        nextButton.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        nextButton.setForeground(new java.awt.Color(255, 255, 255));
        nextButton.setText("Next");
        nextButton.setBorder(null);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        addButton.setBackground(new java.awt.Color(36, 208, 124));
        addButton.setFont(new java.awt.Font("Cuprum", 0, 16)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add");
        addButton.setBorder(null);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(440, 440, 440))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(466, 466, 466))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String patientId = patientIdText.getText();
        String firstName = firstNameText.getText();
        String lastName = lastNameText.getText();
        String nic = nicText.getText();
        String dob = (String) yearComboBox.getSelectedItem() + "-" + (String) monthComboBox.getSelectedItem() + "-" + (String) dateComboBox.getSelectedItem();
        String gender = (String) genderComboBox.getSelectedItem();
        String bloodGroup = bloodGroupTest.getText();
        String alergyDetails = alergyDetailsText.getText();
        String specialNotes = specialNotesText.getText();
        String code = codeText.getText();
        String street = streetText.getText();
        String city = cityText.getText();
        String district = districtText.getText();

        Patient patient = new Patient(patientId, firstName, lastName, nic, dob, gender, bloodGroup, alergyDetails, specialNotes, code, street, city, district);

        String residence = residenceTest.getText();
        String mobile = mobileTest.getText();

        PatientContact patientContact = new PatientContact(patientId, residence, mobile);

        String relationship = relationshipText.getText();
        String name = nameText.getText();
        String eMobile = eMobileText.getText();
        String eResidence = eResidenceText.getText();

        EmergencyContact emergencyContact = new EmergencyContact(patientId, relationship, name, mobile, residence);

        try {
            boolean updatePatient = PatientController.updatePatient(patient, patientContact, emergencyContact);
            if (updatePatient) {
                JOptionPane.showMessageDialog(this, "Successfull!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed!");
                return;
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PatientDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PatientDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

//        firstNameText.setText("");
//        lastNameText.setText("");
//        nicText.setText("");
//        specialNotesText.setText("");
//        alergyDetailsText.setText("");
//        bloodGroupTest.setText("");
        AdmissionForm admission = new AdmissionForm();
        admission.setVisible(true);
        homePanel.setLayout(new BorderLayout());
        homePanel.removeAll();
        homePanel.add(admission);
        homePanel.validate();
        homePanel.repaint();

        AdmissionForm.patientIdText.setText(patientIdText.getText());

        AdmissionForm.nameText.setText(firstNameText.getText() + " " + lastNameText.getText());

        AdmissionForm.nicText.setText(nicText.getText());

    }//GEN-LAST:event_updateButtonActionPerformed

    private void dateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateComboBoxActionPerformed

    private void monthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthComboBoxActionPerformed

    private void patientIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIdTextActionPerformed
        String patientId = patientIdText.getText();
        try {
            Patient patient = PatientController.searchPatient(patientId);
            PatientContact patientContact = PatientContactController.searchPatientContact(patientId);
            EmergencyContact emergencyContact = EmergencyContactController.searchPatient(patientId);

            if (patient != null) {
                patientIdText.setText(patient.getPatientId());
                firstNameText.setText(patient.getFirstName());
                lastNameText.setText(patient.getLastName());
                nicText.setText(patient.getNic());
                bloodGroupTest.setText(patient.getBloodGroup());
                alergyDetailsText.setText(patient.getAlergyDetails());
                specialNotesText.setText(patient.getSpecialNotes());
                codeText.setText(patient.getPostalCode());
                streetText.setText(patient.getStreet());
                cityText.setText(patient.getCity());
                districtText.setText(patient.getDistrict());

                if (patientContact != null) {
                    mobileTest.setText(patientContact.getMobile());
                    residenceTest.setText(patientContact.getResidence());
                }

                if (emergencyContact != null) {
                    relationshipText.setText(emergencyContact.getRelationship());
                    nameText.setText(emergencyContact.getName());
                    eMobileText.setText(emergencyContact.getMobile());
                    eResidenceText.setText(emergencyContact.getResidence());
                } else {
                    JOptionPane.showMessageDialog(this, "No such patient found!");
                }

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PatientDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PatientDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_patientIdTextActionPerformed

    private void lastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextActionPerformed

    private void bloodGroupTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupTestActionPerformed

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextActionPerformed

    private void mobileTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileTestActionPerformed

    private void residenceTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residenceTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_residenceTestActionPerformed

    private void cityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextActionPerformed

    private void codeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeTextActionPerformed

    private void streetTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetTextActionPerformed

    private void districtTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_districtTextActionPerformed

    private void relationshipTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationshipTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relationshipTextActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
//        AdmissionForm admission = new AdmissionForm();
//        admission.setVisible(true);
//        homePanel.setLayout(new BorderLayout());
//        homePanel.removeAll();
//        homePanel.add(admission);
//        homePanel.validate();
//        homePanel.repaint();
//
//        String patientId = patientIdText.getText();
//        AdmissionForm.patientIdText.setText(patientId);
//
//        String name = firstNameText.getText() + " " + lastNameText.getText();
//        AdmissionForm.nameText.setText(name);
//
//        String nic = nicText.getText();
//        AdmissionForm.nicText.setText(nic);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String patientId = patientIdText.getText();
        String firstName = firstNameText.getText();
        String lastName = lastNameText.getText();
        String nic = nicText.getText();
        String dob = (String) yearComboBox.getSelectedItem() + "-" + monthComboBox.getSelectedItem() + "-" + dateComboBox.getSelectedItem();
        String gender = (String) genderComboBox.getSelectedItem();
        String bloodGroup = bloodGroupTest.getText();
        String alergyDetails = alergyDetailsText.getText();
        String specialNotes = specialNotesText.getText();
        String postalCode = codeText.getText();
        String street = streetText.getText();
        String city = cityText.getText();
        String district = districtText.getText();

        Patient patient = new Patient(patientId, firstName, lastName, nic, dob, gender, bloodGroup, alergyDetails, specialNotes, postalCode, street, city, district);

        String residence = residenceTest.getText();
        String mobile = mobileTest.getText();

        PatientContact patientContact = new PatientContact(patientId, residence, mobile);

        String relationship = relationshipText.getText();
        String name = nameText.getText();
        String eMobile = eMobileText.getText();
        String eResidence = eResidenceText.getText();

        EmergencyContact emergencyContact = new EmergencyContact(patientId, relationship, name, mobile, residence);

        try {
            boolean addPatient = PatientController.addPatient(patient, patientContact, emergencyContact);
            if (addPatient) {
                JOptionPane.showMessageDialog(this, "Succssfull");
            } else {
                JOptionPane.showMessageDialog(this, "Failed");
            }
        } catch (SQLException ex) {
            Logger.getLogger(PatientDetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PatientDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

        AdmissionForm admission = new AdmissionForm();
        admission.setVisible(true);
        homePanel.setLayout(new BorderLayout());
        homePanel.removeAll();
        homePanel.add(admission);
        homePanel.validate();
        homePanel.repaint();

        AdmissionForm.patientIdText.setText(patientIdText.getText());
        AdmissionForm.nameText.setText(firstNameText.getText() + " " + lastNameText.getText());
        AdmissionForm.nicText.setText(nicText.getText());
    }//GEN-LAST:event_addButtonActionPerformed

    private void eMobileTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMobileTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMobileTextActionPerformed

    private void eResidenceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eResidenceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eResidenceTextActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String patientId = patientIdText.getText();
        try {
            Patient patient = PatientController.searchPatient(patientId);
            PatientContact patientContact = PatientContactController.searchPatientContact(patientId);
            EmergencyContact emergencyContact = EmergencyContactController.searchPatient(patientId);

            if (patient != null) {
                patientIdText.setText(patient.getPatientId());
                firstNameText.setText(patient.getFirstName());
                lastNameText.setText(patient.getLastName());
                nicText.setText(patient.getNic());
                bloodGroupTest.setText(patient.getBloodGroup());
                alergyDetailsText.setText(patient.getAlergyDetails());
                specialNotesText.setText(patient.getSpecialNotes());
                codeText.setText(patient.getPostalCode());
                streetText.setText(patient.getStreet());
                cityText.setText(patient.getCity());
                districtText.setText(patient.getDistrict());

                if (patientContact != null) {
                    mobileTest.setText(patientContact.getMobile());
                    residenceTest.setText(patientContact.getResidence());
                }

                if (emergencyContact != null) {
                    relationshipText.setText(emergencyContact.getRelationship());
                    nameText.setText(emergencyContact.getName());
                    eMobileText.setText(emergencyContact.getMobile());
                    eResidenceText.setText(emergencyContact.getResidence());
                } else {
                    JOptionPane.showMessageDialog(this, "No such patient found!");
                }
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(PatientDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextArea alergyDetailsText;
    private javax.swing.JTextField bloodGroupTest;
    private javax.swing.JTextField cityText;
    private javax.swing.JTextField codeText;
    private javax.swing.JComboBox<String> dateComboBox;
    private javax.swing.JTextField districtText;
    private javax.swing.JTextField eMobileText;
    private javax.swing.JTextField eResidenceText;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JTextField mobileTest;
    private javax.swing.JComboBox<String> monthComboBox;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton nextButton;
    private javax.swing.JTextField nicText;
    public static javax.swing.JTextField patientIdText;
    private javax.swing.JTextField relationshipText;
    private javax.swing.JTextField residenceTest;
    public static javax.swing.JButton searchButton;
    private javax.swing.JTextArea specialNotesText;
    private javax.swing.JTextField streetText;
    private javax.swing.JButton updateButton;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables

    private void fillPatientIdText() throws SQLException, ClassNotFoundException {
        String newId = IDGenerator.getNewId("Patient", "PatientID", "P");
        patientIdText.setText(newId);
    }
}
